DROP TABLE IF EXISTS dnvs;

CREATE TABLE dnvs (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  chromosome INTEGER,
  position INTEGER,
  ref TEXT,
  alt TEXT,
  sample TEXT,
  status TEXT,
  cohort TEXT,
  cohort_condition TEXT,
  gene TEXT,
  consequence TEXT,
  transcript TEXT,
  aa_change TEXT,
  dna_change TEXT,
  cadd REAL,
  revel REAL,
  gmvp REAL,
  MisFit_D REAL,
  MisFit_S REAL,
  AlphaMissense REAL,
  spliceai REAL,
  gnomAD4_AC INTEGER,
  gnomAD4_AN INTEGER,
  gnomAD4_AF REAL,
  topmed_af REAL,
  vid TEXT UNIQUE);